spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/study?a=fllowPublicKeyRetrieval=true&useSSLalse&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456

mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
#  config-location: classpath:application-mysql.yml

# 数据库表名
#mysql:
#  table:
#    name:
#      - user
#      - role