spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  ### 被监控模块配置 ###
  boot:
    ## 注册服务名  spring boot admin
    admin:
      client:
        instance:
          name: service-main
        url: http://127.0.0.1:8999
        username: admin
        password: admin

# 接口文档增强
knife4j:
  enable: true
#  production: true # 开启屏蔽文档资源

#  endpoints config
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

# JWT配置
jwt:
  # 密匙Key
  secret: Template-boot
  # HeaderKey  Authorization
  tokenHeader: Token
  # Token前缀
  tokenPrefix: Bearer
  # 过期时间，单位秒
  expiration: 300
  # 刷新时间，单位天
  refreshTime: 1
  # 配置白名单（不需要认证）
  antMatchers: /login/**

