spring:
  application:
    name: gardenia-main-service
  profiles:
    active: '@profile.name@'
    include:
    - mysql
    - log
  security:
    user:
      name: admin
      password: admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  ### 被监控模块配置 ###
#  boot:
#    ## 注册服务名  spring boot admin
#    admin:
#      client:
#        instance:
#          name: service-main
#          service-base-url: http://127.0.0.1:8999
#        url: http://127.0.0.1:8999
#        username: admin
#        password: admin

# Log
logging:
  files-path: logs/gardenia
  logback:
    rolling policy:
      file-name-pattern:
  level:
    org.springframework.r2dbc: DEBUG

# 接口文档增强
springdoc:
  api-docs:
    enabled: true
    path: /gardenia.html
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on
openapi: "4.5.0"
info:
  title: Gardenia Admin
  description: "This is an API program for teaching"
  version: '1.1'
  termsOfService: "https://Gardenia.apifox.cn/"
  contact:
    name: "api Gardenia"
    url: "http://Gardenia.cn"
    email: "Gardenia@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://springdoc.org"
paths: {}


# 动态配置 Mapper (占位符)
mybatis:
  mapperScanner:
    basePackage: com.zy.service.**.mapper*

# mybatis-plus 配置
mybatis-plus:
#  mapper-locations:
#    - classpath:com/zy/service/**/mapper/xml/*Mapper.xml
#  global-config:
#    db-config:
#      id-type: auto
#    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  endpoints config
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

# JWT配置
jwt:
  # 密匙Key
  secret: Template-boot
  # HeaderKey  Authorization
  tokenHeader: Token
  # Token前缀
  tokenPrefix: Bearer
  # 过期时间，单位秒
  expiration: 300
  # 刷新时间，单位天
  refreshTime: 1
  # 配置白名单（不需要认证）
  antMatchers: /login/**,/**
